spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/evaclub
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgeSLDialect
  flyway:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

application:
  mailing:
    frontend:
      activation-url: ${ACTIVATION_URL}
  cors:
    origins: ${CORS_ORIGIN}
  file:
    upload:
      photos-output-path: ./uploads

server:
  port: 8088

mercadopago:
  access-token: ${MP_ACCESS_TOKEN}
  success-url: ${MP_SUCCESS_URL}
  failure-url: ${MP_FAILURE_URL}
  pending-url: ${MP_PENDING_URL}
